spring.application.name=notification-service
server.port=8084

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/notificationdb
spring.r2dbc.username=postgres
spring.r2dbc.password=Vfvf31101988

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.url=jdbc:postgresql://localhost:5432/notificationdb
spring.liquibase.user=postgres
spring.liquibase.password=Vfvf31101988

spring.sql.init.mode=never