spring.application.name=payment-service
server.port=8085

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/paymentdb
spring.r2dbc.username=postgres
spring.r2dbc.password=Vfvf31101988

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.url=jdbc:postgresql://localhost:5432/paymentdb
spring.liquibase.user=postgres
spring.liquibase.password=Vfvf31101988

spring.sql.init.mode=never